"""
baseline_inference.py — Baseline agent using the OpenAI API client.

This script shows how a GRPO rollout works against the ETL environment.
Run from Colab or any Jupyter notebook environment.

Usage:
    python baseline_inference.py --task easy --seed 42

For GRPO training, this becomes the rollout_func passed to GRPOTrainer.
The environment runs over HTTP (or local) — same API either way.
"""
import argparse
import json
import os
from typing import Dict, Any

from openai import OpenAI

# ── Try local import first, then remote ──────────────────────
try:
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    from server.environment import ETLEnvironment
    from models import ETLAction
    USE_LOCAL = True
except ImportError:
    USE_LOCAL = False
    # Use OpenEnv HTTP client
    from etl_env import ETLEnv, ETLAction  # generated by openenv push


# ─────────────────────────────────────────────────────────────
# System prompt (the Wordle system prompt equivalent)
# ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert data engineer. You will receive a broken dataset
and must clean it to match a target schema.

AVAILABLE TOOLS (use exactly one per turn):
  profile_column   — {"column": "<col_name>"}
  inspect_sample   — {"n_rows": 5}
  write_transform  — {"code": "<pandas code using df variable>"}
  execute_transform — {}
  validate         — {"checks": ["null_check", "type_check", "range_check", "uniqueness_check"]}
  fix_transform    — {"new_code": "<revised code>", "error_msg": "<error you saw>"}
  load_to_target   — {}
  submit           — {"reasoning": "<explain what you fixed and why>"}

STRATEGY:
1. Profile suspicious columns first (especially after seeing the schema)
2. Write ONE comprehensive transform (don't fix one thing at a time)
3. Execute → if error, use fix_transform
4. Validate → check scores
5. If scores < 0.9, revise transform and retry
6. load_to_target when satisfied, then submit with clear reasoning

IMPORTANT:
- Transform code must assign result back to `df` variable
- Respond with ONLY valid JSON: {"tool": "<name>", "params": {...}, "reasoning": "<why>"}
- Do NOT include any other text outside the JSON
"""


def format_observation(obs: Dict) -> str:
    """Convert observation dict into a concise prompt for the LLM."""
    lines = [
        f"=== STEP {obs['step']} | {obs['steps_remaining']} steps remaining ===",
        f"Dataset: {obs['row_count']} rows",
        f"Current schema: {json.dumps(obs['schema_current'], indent=2)}",
        f"Target schema: {json.dumps({k: v for k, v in obs['schema_target'].items()}, indent=2)}",
    ]

    if obs.get("validation_scores"):
        lines.append(f"Validation scores: {json.dumps(obs['validation_scores'])}")

    if obs.get("last_tool_output"):
        lines.append(f"Last action result: {obs['last_tool_output']}")

    if obs.get("schema_drift_event"):
        lines.append(f"⚠️  SCHEMA CHANGE DETECTED: {obs['schema_drift_event']}")

    if obs.get("dataset_sample"):
        sample_str = json.dumps(obs["dataset_sample"][:3], default=str)
        lines.append(f"Sample rows (first 3): {sample_str}")

    return "\n".join(lines)


def run_episode(
    client: OpenAI,
    env,
    task_id: str = "easy",
    seed: int = 42,
    model: str = "gpt-4o-mini",
    verbose: bool = True,
) -> Dict[str, Any]:
    """Run one full episode. Returns the final info dict with scores."""

    # Reset environment
    if USE_LOCAL:
        obs_obj = env.reset(task_id=task_id, seed=seed)
        obs = obs_obj.model_dump()
    else:
        result = env.reset(task_id=task_id, seed=seed)
        obs = result.observation.__dict__

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    total_reward = 0.0
    step = 0

    while True:
        # Build user message from observation
        user_content = format_observation(obs)
        messages.append({"role": "user", "content": user_content})

        # Get LLM action
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0.3,
            max_tokens=500,
        )
        raw = response.choices[0].message.content.strip()
        messages.append({"role": "assistant", "content": raw})

        # Parse action
        try:
            action_dict = json.loads(raw)
        except json.JSONDecodeError:
            # Try to extract JSON from response
            import re
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                action_dict = json.loads(match.group())
            else:
                action_dict = {"tool": "submit", "params": {}, "reasoning": "Parse error"}

        if verbose:
            print(f"[Step {step+1}] Tool: {action_dict.get('tool')} | "
                  f"Params: {action_dict.get('params', {})} | "
                  f"Reasoning: {action_dict.get('reasoning', '')[:80]}")

        # Execute in environment
        action = ETLAction(
            tool=action_dict.get("tool", "submit"),
            params=action_dict.get("params", {}),
            reasoning=action_dict.get("reasoning", ""),
        )

        if USE_LOCAL:
            result = env.step(action)
            obs_obj, reward, done, info = result
            obs = obs_obj.model_dump()
        else:
            result = env.step(action)
            obs = result.observation.__dict__
            reward = result.reward
            done = result.done
            info = {}

        total_reward += (reward or 0.0)
        step += 1

        if verbose:
            print(f"         Reward: {reward:.3f} | Cumulative: {total_reward:.3f}")

        if done:
            break

    if verbose:
        print(f"\n=== Episode Complete ===")
        print(f"Final score: {info.get('final_score', total_reward):.4f}")
        if "grader_breakdown" in info:
            for k, v in info["grader_breakdown"].items():
                if isinstance(v, float):
                    print(f"  {k}: {v:.4f}")
        print(f"Steps taken: {step}/{env.TASK_MAX_STEPS[task_id]}")

    return info


# ─────────────────────────────────────────────────────────────
# GRPO rollout function (what TRL calls during training)
# ─────────────────────────────────────────────────────────────

def make_rollout_func(env, task_id: str = "easy", max_turns: int = 15):
    """
    Returns a rollout_func compatible with TRL's GRPOTrainer.

    Usage:
        trainer = GRPOTrainer(
            model=model,
            reward_funcs=[],
            rollout_func=make_rollout_func(env, task_id="medium"),
            ...
        )
    """
    def rollout_func(prompts, trainer):
        """Play one ETL episode and return GRPO-compatible trajectory."""
        from trl import GRPOTrainer

        if USE_LOCAL:
            obs_obj = env.reset(task_id=task_id)
            obs = obs_obj.model_dump()
        else:
            result = env.reset(task_id=task_id)
            obs = result.observation.__dict__

        prompt_ids = []
        completion_ids = []
        logprobs = []
        rewards = []
        messages = [{"role": "system", "content": SYSTEM_PROMPT}]

        for turn in range(max_turns):
            user_content = format_observation(obs)
            messages.append({"role": "user", "content": user_content})

            # Use trainer's model for generation
            tokenized = trainer.tokenizer.apply_chat_template(
                messages, tokenize=True, return_tensors="pt", add_generation_prompt=True
            )
            gen_output = trainer.model.generate(
                tokenized.to(trainer.model.device),
                max_new_tokens=300,
                temperature=0.7,
                do_sample=True,
            )
            completion = gen_output[:, tokenized.shape[1]:]
            completion_text = trainer.tokenizer.decode(completion[0], skip_special_tokens=True)
            messages.append({"role": "assistant", "content": completion_text})

            try:
                action_dict = json.loads(completion_text)
            except Exception:
                action_dict = {"tool": "submit", "params": {}, "reasoning": "parse error"}

            action = ETLAction(**action_dict)

            if USE_LOCAL:
                obs_obj, reward, done, info = env.step(action)
                obs = obs_obj.model_dump()
            else:
                result = env.step(action)
                obs, reward, done, info = result.observation.__dict__, result.reward, result.done, {}

            prompt_ids.append(tokenized)
            completion_ids.append(completion)
            rewards.append(reward or 0.0)

            if done:
                break

        return {
            "prompt_ids": prompt_ids,
            "completion_ids": completion_ids,
            "logprobs": logprobs,
            "rewards": rewards,
        }

    return rollout_func


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", default="easy", choices=["easy", "medium", "hard"])
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--all-tasks", action="store_true")
    args = parser.parse_args()

    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    if USE_LOCAL:
        env = ETLEnvironment(openai_api_key=os.environ.get("OPENAI_API_KEY"))
    else:
        env = ETLEnv(base_url=os.environ.get("ETL_ENV_URL", "http://localhost:8000"))

    tasks = ["easy", "medium", "hard"] if args.all_tasks else [args.task]
    results = {}
    for task in tasks:
        print(f"\n{'='*50}\nTask: {task.upper()}\n{'='*50}")
        info = run_episode(client, env, task_id=task, seed=args.seed, model=args.model)
        results[task] = info.get("final_score", 0.0)

    print(f"\n=== BASELINE SCORES ===")
    for task, score in results.items():
        print(f"  {task:8s}: {score:.4f}")